targets:
  $default:
    builders:
      flutter_code_generators|annotations:
        enabled: true      

builders:
  # The next three builders are `SharedPartBuilder` instances.
  # Notice they each have
  # `build_extensions` set to a `NAME.g.part` file.
  #    NAME corresponds to the second argument to the SharedPartBuilder ctor.
  #    `.g.part` is the extension expected of SharedPartBuilder.
  # `build_to: cache` - the output is not put directly into the project
  # `applies_builders` - uses the `combining_builder` from `source_gen` to
  #   combine the parts from each builder into one part file.

  modelGenerator:
    target: ":modelGenerator"
    import: "package:flutter_code_generators/generators.dart"
    builder_factories: ["generateModelMethods"]
    build_extensions: { ".dart": [".kg_model.dart"] }
    auto_apply: dependents
    build_to: source

  repositoryGenerator:
    target: ":repositoryGenerator"
    import: "package:flutter_code_generators/generators.dart"
    builder_factories: ["generateRepositoryClass"]
    build_extensions: { ".dart": [".kg_repository.dart"] }
    auto_apply: dependents
    build_to: source  

  databaseGenerator:
    target: ":databaseGenerator"
    import: "package:flutter_code_generators/generators.dart"
    builder_factories: ["generateDatabaseClass"]
    build_extensions: { ".dart": [".kg_database.dart"] }
    auto_apply: dependents
    build_to: source    

  # repositoryGenerator:
  #   target: ":repositoryGenerator"
  #   import: "package:flutter_code_generators/generators.dart"
  #   builder_factories: ["generateRepositoryBaseMethods"]
  #   build_extensions: { ".dart": [".base.dart"] }
  #   auto_apply: dependents
  #   build_to: source    
    
  # firebaseBuilder:
  #   target: ":firebaseBuilder"
  #   import: "package:flutter_code_generators/generators.dart"
  #   builder_factories: ["firebaseBuilder"]
  #   build_extensions: { ".dart": [".firebase.dart"] }
  #   auto_apply: dependents
  #   build_to: source

  # blocBuilder:
  #   target: ":blocBuilder"
  #   import: "package:models_generators/builder.dart"
  #   builder_factories: ["blocBuilder"]
  #   build_extensions: { ".model.dart": [".e.dart"] }
  #   auto_apply: dependents
  #   build_to: source

  # blocsBuilder:
  #   target: ":blocsBuilder"
  #   import: "package:models_generators/builder.dart"
  #   builder_factories: ["blocsBuilder"]
  #   build_extensions: { ".model.dart": [".e.dart"] }
  #   auto_apply: dependents
  #   build_to: source