builders:
  # The next three builders are `SharedPartBuilder` instances.
  # Notice they each have
  # `build_extensions` set to a `NAME.g.part` file.
  #    NAME corresponds to the second argument to the SharedPartBuilder ctor.
  #    `.g.part` is the extension expected of SharedPartBuilder.
  # `build_to: cache` - the output is not put directly into the project
  # `applies_builders` - uses the `combining_builder` from `source_gen` to
  #   combine the parts from each builder into one part file.

  model_generator:    
    import: "package:flutter_code_generator/builder.dart"
    builder_factories: ["modelGeneratorBuilder"]
    build_extensions: { ".dart": ["model_generator.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

  repository_generator:    
    import: "package:flutter_code_generator/builder.dart"
    builder_factories: ["repositoryGeneratorBuilder"]
    build_extensions: { ".dart": ["repository_generator.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

# #   # databaseGenerator:
# #   #   target: ":databaseGenerator"
# #   #   import: "package:flutter_code_generators/generators.dart"
# #   #   builder_factories: ["generateDatabaseClass"]
# #   #   build_extensions: { ".dart": [".kg_database.dart"] }
# #   #   auto_apply: dependents
# #   #   build_to: source    

# #   # repositoryGenerator:
# #   #   target: ":repositoryGenerator"
# #   #   import: "package:flutter_code_generators/generators.dart"
# #   #   builder_factories: ["generateRepositoryBaseMethods"]
# #   #   build_extensions: { ".dart": [".base.dart"] }
# #   #   auto_apply: dependents
# #   #   build_to: source    
    
# #   # firebaseBuilder:
# #   #   target: ":firebaseBuilder"
# #   #   import: "package:flutter_code_generators/generators.dart"
# #   #   builder_factories: ["firebaseBuilder"]
# #   #   build_extensions: { ".dart": [".firebase.dart"] }
# #   #   auto_apply: dependents
# #   #   build_to: source

# #   # blocBuilder:
# #   #   target: ":blocBuilder"
# #   #   import: "package:models_generators/builder.dart"
# #   #   builder_factories: ["blocBuilder"]
# #   #   build_extensions: { ".model.dart": [".e.dart"] }
# #   #   auto_apply: dependents
# #   #   build_to: source

# #   # blocsBuilder:
# #   #   target: ":blocsBuilder"
# #   #   import: "package:models_generators/builder.dart"
# #   #   builder_factories: ["blocsBuilder"]
# #   #   build_extensions: { ".model.dart": [".e.dart"] }
# #   #   auto_apply: dependents
# #   #   build_to: source