name: flutter_code_generator
description: Getters and setters to save variables to and from Map
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  analyzer: ^6.4.1
  source_gen: ^1.2.9
  build: ^2.4.1

dev_dependencies:  
  build_runner: ^2.4.9
  test: ^1.25.4